### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by iamAbhishekkumar** [codex-iter/website-backend#1]

**Comment by iamAbhishekkumar** [comment]
Added Routes for Event page. 
Commits : 
f682eca4ec12dcd6e8b510c1bacb23202657db40
46822cb119667b045cd8a55cadc649b23dbb6669

**Comment by MartyMiniac** [comment]
fullyworking event routes added in 2b9ea33e6d1631d017bd300e85a60fa122ca1b0a
