### ISSUE TITLE
Newer files might replace older if both the files share the same name while uploading to firebase

### ISSUE THREAD

**Issue by MartyMiniac** [codex-iter/website-backend#3]
https://github.com/codex-iter/website-backend/blob/46822cb119667b045cd8a55cadc649b23dbb6669/model/event.py#L21
This line needs to be updated..... the possible solution would be to implement  uuid to be set as file name so as to guarantee the file name is unique each time. Another way would be to create a hash of the file and use that as the name of the file for in case the file is duplicate the space is not compromised

**Comment by iamAbhishekkumar** [comment]
Added a timestamp along with upload file name, so that it acts as a unique name every time.

**Comment by MartyMiniac** [comment]
need to rework on this due to change in project structure

**Comment by MartyMiniac** [comment]
added file hashing in using md5 hashing in 2b9ea33e6d1631d017bd300e85a60fa122ca1b0a
the file name on the cloud static host is the md5 hash of the file. this will hopefully solve the duplication of files saving space on firestore.
